// on doit afficher tous les composant grahique, simple et complexes.
export const htmlComponent = [
  {
    _id: 1,
    type: 'Text',
    isCustomised: true,
  },
  {
    _id: 2,
    type: 'List',
    isCustomised: true,
  },
  {
    _id: 3,
    type: 'DateTime',
    isCustomised: true,
  },
  {
    _id: 4,
    type: 'Paragraphe',
    isCustomised: true,
  },
  {
    _id: 5,
    type: 'TimeSpan',
    isCustomised: true,
  },
  {
    _id: 6,
    type: 'Boolean',
    isCustomised: true,
  },
  {
    _id: 7,
    type: 'Time',
    isCustomised: true,
  },
  {
    _id: 8,
    type: 'User',
    isCustomised: true,
  },
];

export const html5InputType = {
  None: 0,
  Text: 1,
  Password: 2,
  Radio: 3,
  CheckBox: 4,
  Color: 5,
  Date: 6,
  Datetime: 7,
  DatetimeLocal: 8,
  Email: 9,
  Month: 10,
  Number: 11,
  Range: 12,
  Search: 13,
  Tel: 14,
  Time: 15,
  Url: 16,
  Week: 17,
  Decimal: 18,
};

export const type = {
  None: 0,
  Date: 1,
  Boolean: 2,
  Paragraphe: 3,
  Numeric: 4,
  List: 5,
  String: 6,
  TimeSpan: 7,
  // ItemType: 8,
  Utilisateur: 12,
  Decimal: 13,
};

export const fieldCategory = {
  Service: 0,
  Utilisateur: 1,
  Groupe: 2,
};

export const fieldReference = {
  None: 0, // champs non système, défini par l'utiliseur
  Title: 1,
  Status: 5,
  ID: 6,
  CreatedDate: 7,
  EndedDate: 8,
  Agent_Responsable: 9,
  Contact_Responsable: 10,
  Creator: 11,
  Agent_Observator: 12,
  Contact_Observator: 13,
  Ticket_Log: 14,
  Ticket_Comment: 15,
  Attachment: 16,
  Parent: 17,
  Product: 18,
  Category: 19, // workItemType
  Canal: 20,
  Agent_Assigned_To: 21,
  UpdatedDate: 22,
  ElapsedTime: 23,
  RemainingTime: 24,
  Linked_Ticket: 25,
  Global_SLA: 26,
  Update_Canal: 27,
  User_FirstName: 28,
  User_LastName: 29,
  User_Email: 30,
  User_FixPhone: 31,
  User_Fax: 32,
  User_Gender: 33,
  User_Actif: 34,
  User_MobilePhone: 35,
  User_UpdatedDate: 36,
  User_CreatedDate: 37,
  User_Address_Address1: 38,
  User_Address_Address2: 39,
  User_Address_City: 40,
  User_Address_PostaleCode: 41,
  User_Address_Region: 42,
  User_Address_Country: 43,
  Group_Name: 44,
  Group_Description: 45,
  Group_Actif: 46,
  Group_UpdatedDate: 47,
  Group_CreatedDate: 48,
  Group_Address_Address1: 49,
  Group_Address_Address2: 50,
  Group_Address_City: 51,
  Group_Address_PostaleCode: 52,
  Group_Address_Region: 53,
  Group_Address_Country: 54,
  Group_Type: 55,
  Application: 56,
  Intervention: 57,
  Previous_Step: 58,
  Contact_Responsable_Groupe: 59,
  ItemPrefixe: 60,
  Impact: 61,
  Urgence: 62,
  Priority: 63,
};

export default { html5InputType, type, fieldReference, fieldCategory };
